server:
  port: 9000
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  application:
    name: service-order

job:
  baseSleepTimeMilliseconds: 1000
  maxSleepTimeMilliseconds: 3000
  sessionTimeoutMilliseconds: 60000
  connectionTimeoutMilliseconds: 60000
  maxRetries: 3
  zkServerList: 127.0.0.1:2181
  namespace: rtp-core-job
  job1Shards: 1
  job1Cron: 0/5 * * * * ?
  job2Shards: 2
  job2Cron: 0/10 * * * * ?

logging:
  config: classpath:logback.xml

#xxl-job配置
xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      address: ''
      appname: test-execute-job
      ip: ''
      logpath: /Users/liuwq/IdeaProjects/xxl-job/logs/jobhandler
      logretentiondays: 30
      port: 9998

#minio相关配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: admin
  secretKey: abc12345
  bucketName: mybucket
  #存储文件夹
  folder: myfolder/